package guia2_ejercicio4;

import java.util.*;

public class Menu extends javax.swing.JFrame {
    public static TreeSet<Productos> listP = new TreeSet<>();
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jproductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jbusquedaXr = new javax.swing.JMenuItem();
        jbuquedaXn = new javax.swing.JMenuItem();
        jbusquedaXp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setForeground(new java.awt.Color(255, 0, 0));
        jMenu1.setText("Administrador");

        jproductos.setText("Productos");
        jproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jproductosActionPerformed(evt);
            }
        });
        jMenu1.add(jproductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setForeground(new java.awt.Color(255, 0, 0));
        jMenu2.setText("Consultas");

        jbusquedaXr.setText("PorRubro");
        jbusquedaXr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbusquedaXrActionPerformed(evt);
            }
        });
        jMenu2.add(jbusquedaXr);

        jbuquedaXn.setText("PorNombre");
        jbuquedaXn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuquedaXnActionPerformed(evt);
            }
        });
        jMenu2.add(jbuquedaXn);

        jbusquedaXp.setText("PorPrecio");
        jbusquedaXp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbusquedaXpActionPerformed(evt);
            }
        });
        jMenu2.add(jbusquedaXp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbusquedaXrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbusquedaXrActionPerformed
        // TODO add your handling code here:
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.repaint();
        BusquedaPorRubro bpr = new BusquedaPorRubro();
        bpr.setVisible(true);
        this.jDesktopPane1.add(bpr);
        this.jDesktopPane1.moveToFront(bpr); 
    }//GEN-LAST:event_jbusquedaXrActionPerformed

    private void jbuquedaXnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuquedaXnActionPerformed
        // TODO add your handling code here:
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.repaint();
        BusquedaPorNombre bpn = new BusquedaPorNombre();
        bpn.setVisible(true);
        this.jDesktopPane1.add(bpn);
        this.jDesktopPane1.moveToFront(bpn);
    }//GEN-LAST:event_jbuquedaXnActionPerformed

    private void jbusquedaXpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbusquedaXpActionPerformed
        // TODO add your handling code here:
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.repaint();
        BusquedaPorPrecio bpp = new BusquedaPorPrecio();
        bpp.setVisible(true);
        this.jDesktopPane1.add(bpp);
        this.jDesktopPane1.moveToFront(bpp);
    }//GEN-LAST:event_jbusquedaXpActionPerformed

    private void jproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jproductosActionPerformed
        // TODO add your handling code here:
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.repaint();
        GestionDeProductos gdp = new GestionDeProductos();
        gdp.setVisible(true);
        this.jDesktopPane1.add(gdp);
        this.jDesktopPane1.moveToFront(gdp);
    }//GEN-LAST:event_jproductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jbuquedaXn;
    private javax.swing.JMenuItem jbusquedaXp;
    private javax.swing.JMenuItem jbusquedaXr;
    private javax.swing.JMenuItem jproductos;
    // End of variables declaration//GEN-END:variables

private void cargarProductos(){
    listP.add(new Productos(1, "arroz", 450.25, 25, Categoria.COMESTIBLE));
    listP.add(new Productos(2, "fideos", 300.80, 30, Categoria.COMESTIBLE));
    listP.add(new Productos(30, "desedorante", 400.80, 40, Categoria.PERFUMERIA));
    listP.add(new Productos(28, "jabon", 700.80, 8, Categoria.PERFUMERIA));
    listP.add(new Productos(25, "lavandina", 380.80, 10, Categoria.LIMPIEZA));
    listP.add(new Productos(21, "detergente", 600.80, 30, Categoria.LIMPIEZA));
    listP.add(new Productos(10, "dentífrico", 400.80, 0, Categoria.LIMPIEZA));
}

}
